#!/usr/bin/sh

if [ "$#" -ne 1 ]; then
    echo "Usage: ./add_module <name>"
    exit 1
fi

if [ -e "test_$1.c" ]; then
    echo "Module test_$1 already exists."
    exit 1
fi

touch "./test_$1.c"
echo "#include \"test.h\"

void test_${1}__addTests(void) {
    setModule(\"test_$1\");
}" >> "./test_$1.c"
