#!/usr/bin/sh

if [ "$#" -ne 1 ]; then
    echo "Usage: ./add_module <name>"
    exit 1
fi

$file=./test_modules/test_$1.c

if [ -e $file ]; then
    echo "Module test_$1 already exists."
    exit 1
fi

touch $file
echo "#include \"../test_lib/test.h\"

void test_${1}__addTests(void) {
    testSetModule(\"test_$1\");
}" >> "./test_$1.c"
